services:
  - type: web
    name: quicksaver
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
